GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
"nombre": "Prueba",
"apellido_paterno": "Covey78P",
"apellido_materno": "Hernandez",
"contrasena": 7785
}
###
DELETE http://localhost:9000/api/1 HTTP/1.1
###
PUT http://localhost:9000/api/2 HTTP/1.1
Content-Type: application/json

{
"nombre": "Stephen Covey",
"apellido_paterno": "Covey78P",
"apellido_materno": "Hernandez",
"contrasena": 7785
}